apiVersion: v1
kind: Service
metadata:
  name: {{ include "oobabooga.fullname" . }}
  labels:
    {{- include "oobabooga.labels" . | nindent 4 }}
spec:

  type: {{ .Values.service.type }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  ports:
    - port: {{ .Values.service.webUiPort }}
      targetPort: webui
      protocol: TCP
      name: webui
    - port: {{ .Values.service.apiPort }}
      targetPort: api
      protocol: TCP
      name: api

  selector:
    {{- include "oobabooga.selectorLabels" . | nindent 4 }}
